import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Banner from "components/banner";
import NavBar from "components/navbar/NavBar";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Kobo-roll</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Kobo-roll</h1>
        <NavBar username="user@example.com" />
        <Banner
          title="The Smurfs"
          subTitle="The blue squad"
          imgUrl="/static/smurfs2.jpg"
        />
      </main>
    </div>
  );
};

export default Home;
